version: "2.1"
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
    volumes:
      - /media/podgrab/config:/config
      - /media/navidrome/music/podcasts:/assets
    ports:
      - 56734:8080
    restart: unless-stopped
